version: "3.6"

services:
  backend:
    image: jobs-backend
    container_name: "jobs-backend-onest"
    restart: always
    ports:
      - 4000:3000
    env_file:
      - /home/ubuntu/onest/jobs-backend/.env
